// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzGvPsiL75POWFi1nZRIE2lsXxYaQ7Ykw',
    appId: '1:86093969927:web:dab9dc38bd66e03f3888a2',
    messagingSenderId: '86093969927',
    projectId: 'gfoodappproject',
    authDomain: 'gfoodappproject.firebaseapp.com',
    storageBucket: 'gfoodappproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdfrgdqt4zKQYLmscYEyCFNGiLfKBFr70',
    appId: '1:86093969927:android:842ca3e86dbfc6c33888a2',
    messagingSenderId: '86093969927',
    projectId: 'gfoodappproject',
    storageBucket: 'gfoodappproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf4MkA2J4UIua4us_kwYcbq-olVjC5HpI',
    appId: '1:86093969927:ios:c7cdc05f953c90af3888a2',
    messagingSenderId: '86093969927',
    projectId: 'gfoodappproject',
    storageBucket: 'gfoodappproject.appspot.com',
    androidClientId: '86093969927-rrmj6h8a0j5cr2tb335798r6edveq7fj.apps.googleusercontent.com',
    iosClientId: '86093969927-dumdnts645nn6tbpaagf9v7nk1mhh5of.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf4MkA2J4UIua4us_kwYcbq-olVjC5HpI',
    appId: '1:86093969927:ios:65c4a55af2cb9bf43888a2',
    messagingSenderId: '86093969927',
    projectId: 'gfoodappproject',
    storageBucket: 'gfoodappproject.appspot.com',
    androidClientId: '86093969927-rrmj6h8a0j5cr2tb335798r6edveq7fj.apps.googleusercontent.com',
    iosClientId: '86093969927-qb0kagohe0nbripjd0tg6gvjbck73rq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddeliveryapp.RunnerTests',
  );
}
